In [1]:
import numpy as np

In [2]:
X = np.random.rand(1, 3, 5, 5)

In [3]:
num_filters = 2
filter_size = 3
stride = 1
padding = 1

# Random Filters
W = np.random.randn(num_filters, 3, filter_size, filter_size)

# Bias
b = np.zeros((num_filters, 1))


In [4]:
def im2col(input_data, filter_h, filter_w, stride=1, pad=0):

    N, C, H, W = input_data.shape

    out_h = (H + 2 * pad - filter_h) // stride + 1
    out_w = (W + 2 * pad - filter_w) // stride + 1

    img = np.pad(input_data,
                 [(0,0), (0,0), (pad,pad), (pad,pad)],
                 mode='constant')

    cols = np.zeros((N, C, filter_h, filter_w, out_h, out_w))

    for y in range(filter_h):
        y_max = y + stride * out_h

        for x in range(filter_w):
            x_max = x + stride * out_w

            cols[:, :, y, x, :, :] = img[:, :, y:y_max:stride, x:x_max:stride]

    cols = cols.transpose(0,4,5,1,2,3).reshape(N*out_h*out_w, -1)

    return cols

In [5]:
def im2col(input_data, filter_h, filter_w, stride=1, pad=0):

    N, C, H, W = input_data.shape

    out_h = (H + 2 * pad - filter_h) // stride + 1
    out_w = (W + 2 * pad - filter_w) // stride + 1

    img = np.pad(input_data,
                 [(0,0), (0,0), (pad,pad), (pad,pad)],
                 mode='constant')

    cols = np.zeros((N, C, filter_h, filter_w, out_h, out_w))

    for y in range(filter_h):
        y_max = y + stride * out_h

        for x in range(filter_w):
            x_max = x + stride * out_w

            cols[:, :, y, x, :, :] = img[:, :, y:y_max:stride, x:x_max:stride]

    cols = cols.transpose(0,4,5,1,2,3).reshape(N*out_h*out_w, -1)

    return cols

In [7]:
def conv_forward(X, W, b, stride, pad):
    N, C, H, W_in = X.shape
    F, C, HH, WW = W.shape

    out_h = (H + 2 * pad - HH) // stride + 1
    out_w = (W_in + 2 * pad - WW) // stride + 1

    col = im2col(X, HH, WW, stride, pad)
    col_W = W.reshape(F, -1).T

    out = np.dot(col, col_W) + b.T
    out = out.reshape(N, out_h, out_w, F).transpose(0, 3, 1, 2)
    return out

output = conv_forward(X, W, b, stride, padding)

print("Input Shape :", X.shape)
print("Filter Shape:", W.shape)
print("Output Shape:", output.shape)

print("\nOutput Feature Maps:")
print(output)

Input Shape : (1, 3, 5, 5)
Filter Shape: (2, 3, 3, 3)
Output Shape: (1, 2, 5, 5)

Output Feature Maps:
[[[[-2.00928774 -0.87168071  0.4097047  -1.37823111 -0.81908923]
   [-3.3314188   0.06418139 -0.40343573 -0.98147863  0.43082839]
   [-0.78859407 -0.70164767 -0.85992818  0.60616773 -0.03210957]
   [-3.3135724  -0.14937898 -0.98622924  0.53935816 -1.25787554]
   [-0.08248603  0.2822592   0.47483359  0.37919718  1.32841536]]

  [[ 1.76791705  1.71978576 -0.58621971  1.87774544  0.47461953]
   [-0.22285071 -2.27425769 -0.49518882 -0.90745927 -3.60345808]
   [ 0.21089922  0.15946249 -2.03102154 -0.82457901 -1.09438075]
   [ 1.23354498 -1.70307413 -2.31119305 -0.7016784  -3.51946357]
   [ 0.03467174  0.66858777  1.13672137  2.8998612   1.54156267]]]]
