Bidirectional LSTM from Scratch

In [1]:
import torch
import numpy as np

torch.manual_seed(42)

Input Sequence
 (Sequence Length, Input Features)

In [2]:
seq_len = 5
input_size = 3
hidden_size = 4

X = torch.randn(seq_len, input_size)


ctivation Functions

In [3]:
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

def tanh(x):
    return torch.tanh(x)

Initialize Weights

In [4]:
def initialize():

    W_x = torch.randn(input_size, hidden_size)
    W_h = torch.randn(hidden_size, hidden_size)
    b = torch.zeros(hidden_size)

    return W_x, W_h, b

# Input Gate
Wxi, Whi, bi = initialize()

# Forget Gate
Wxf, Whf, bf = initialize()

# Output Gate
Wxo, Who, bo = initialize()

# Cell Candidate
Wxc, Whc, bc = initialize()

In [5]:
def lstm_forward(sequence):

    h = torch.zeros(hidden_size)
    c = torch.zeros(hidden_size)

    outputs = []

    for t in range(sequence.shape[0]):

        x = sequence[t]

        i = sigmoid(torch.matmul(x, Wxi) + torch.matmul(h, Whi) + bi)

        f = sigmoid(torch.matmul(x, Wxf) + torch.matmul(h, Whf) + bf)

        o = sigmoid(torch.matmul(x, Wxo) + torch.matmul(h, Who) + bo)

        g = tanh(torch.matmul(x, Wxc) + torch.matmul(h, Whc) + bc)

        c = f * c + i * g

        h = o * tanh(c)

        outputs.append(h)

    return torch.stack(outputs)


In [6]:
reverse_sequence = torch.flip(X, dims=[0])


forward_output = lstm_forward(X)

backward_output = lstm_forward(reverse_sequence)

backward_output = torch.flip(backward_output, dims=[0])


In [7]:
BiLSTM_output = torch.cat(
    (forward_output, backward_output),
    dim=1
)

 Display Results

In [8]:
print("Input Sequence Shape")
print(X.shape)

print("\nForward Output Shape")
print(forward_output.shape)

print("\nBackward Output Shape")
print(backward_output.shape)

print("\nBiLSTM Output Shape")
print(BiLSTM_output.shape)

print("\nForward Hidden States")
print(forward_output)

print("\nBackward Hidden States")
print(backward_output)

print("\nFinal BiLSTM Output")
print(BiLSTM_output)

Input Sequence Shape
torch.Size([5, 3])

Forward Output Shape
torch.Size([5, 4])

Backward Output Shape
torch.Size([5, 4])

BiLSTM Output Shape
torch.Size([5, 8])

Forward Hidden States
tensor([[-0.1635, -0.0184, -0.2173,  0.0306],
        [-0.3281,  0.0155,  0.0755,  0.1374],
        [-0.7259, -0.1750, -0.4169,  0.0266],
        [-0.5853,  0.1083, -0.2160,  0.0322],
        [-0.4763, -0.0422,  0.0755,  0.2287]])

Backward Hidden States
tensor([[-0.5630, -0.0511, -0.0299,  0.0886],
        [-0.5392,  0.0188, -0.0203,  0.1783],
        [-0.8030, -0.1625, -0.4518,  0.0219],
        [-0.5220,  0.1282, -0.1610,  0.0341],
        [-0.3164, -0.0303,  0.2011,  0.1586]])

Final BiLSTM Output
tensor([[-0.1635, -0.0184, -0.2173,  0.0306, -0.5630, -0.0511, -0.0299,  0.0886],
        [-0.3281,  0.0155,  0.0755,  0.1374, -0.5392,  0.0188, -0.0203,  0.1783],
        [-0.7259, -0.1750, -0.4169,  0.0266, -0.8030, -0.1625, -0.4518,  0.0219],
        [-0.5853,  0.1083, -0.2160,  0.0322, -0.5220,  0.1282